# Generated by Django 2.2 on 2019-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerID', models.AutoField(db_column='playerID', primary_key=True, serialize=False)),
                ('playerName', models.CharField(db_column='Name', max_length=40)),
                ('playerPhone', models.CharField(db_column='telephone', max_length=11)),
                ('playerMail', models.CharField(db_column='mailbox', max_length=80)),
                ('password', models.CharField(db_column='password', max_length=400)),
            ],
            options={
                'db_table': 'player_table',
            },
        ),
    ]
